In [2]:
import keras as kr

Using TensorFlow backend.


ModuleNotFoundError: No module named 'tensorflow'

In [7]:
import pandas as pd

In [12]:
df = pd.read_csv("dogs.csv")

In [13]:
df

pure  age  weight  height  lifespan
0    True    3    7.94    49.6        15
1    True    7    5.05    63.5        17
2    True    6   16.15    68.2        11
3   False    3   15.50    64.7        12
4   False    3   12.17    59.7        14
..    ...  ...     ...     ...       ...
95  False    4   20.76    52.2        10
96  False    4   17.40    47.5        11
97  False    6   15.60    51.4        12
98  False    3    8.37    54.1        16
99   True    7    9.09    50.3        14

[100 rows x 5 columns]

In [14]:
import numpy as np

In [15]:
df['ispure'] = (df['pure']==True).astype(np.int)
df['isnotpure'] = (df['pure']==False).astype(np.int)
df

pure  age  weight  height  lifespan  ispure  isnotpure
0    True    3    7.94    49.6        15       1          0
1    True    7    5.05    63.5        17       1          0
2    True    6   16.15    68.2        11       1          0
3   False    3   15.50    64.7        12       0          1
4   False    3   12.17    59.7        14       0          1
..    ...  ...     ...     ...       ...     ...        ...
95  False    4   20.76    52.2        10       0          1
96  False    4   17.40    47.5        11       0          1
97  False    6   15.60    51.4        12       0          1
98  False    3    8.37    54.1        16       0          1
99   True    7    9.09    50.3        14       1          0

[100 rows x 7 columns]

In [16]:
inputs = df[['age', 'weight', 'height', 'ispure', 'isnotpure']]
inputs

age  weight  height  ispure  isnotpure
0     3    7.94    49.6       1          0
1     7    5.05    63.5       1          0
2     6   16.15    68.2       1          0
3     3   15.50    64.7       0          1
4     3   12.17    59.7       0          1
..  ...     ...     ...     ...        ...
95    4   20.76    52.2       0          1
96    4   17.40    47.5       0          1
97    6   15.60    51.4       0          1
98    3    8.37    54.1       0          1
99    7    9.09    50.3       1          0

[100 rows x 5 columns]

In [17]:
output = df['lifespan']
output

0     15
1     17
2     11
3     12
4     14
      ..
95    10
96    11
97    12
98    16
99    14
Name: lifespan, Length: 100, dtype: int64

In [46]:
m = kr.models.Sequential()

m.add(kr.layers.Dense(10, input_dim=5, activation="linear"))
#m.add(kr.layers.Dense(30, input_dim=5, activation="sigmoid"))
m.add(kr.layers.Dense(30, activation="linear"))
m.add(kr.layers.Dense(10, activation="linear"))
m.add(kr.layers.Dense(10, activation="linear"))
m.add(kr.layers.Dense(1,  activation="linear"))

m.compile(loss="mean_squared_error", optimizer="adam")

In [47]:
m.fit(inputs, output, epochs=10, batch_size=10)

Epoch 1/10
100/100 [==============================] - 0s 1ms/step - loss: 63.0382
Epoch 2/10
100/100 [==============================] - 0s 190us/step - loss: 30.0819
Epoch 3/10
100/100 [==============================] - 0s 200us/step - loss: 20.0520
Epoch 4/10
100/100 [==============================] - 0s 210us/step - loss: 14.3665
Epoch 5/10
100/100 [==============================] - 0s 220us/step - loss: 12.0730
Epoch 6/10
100/100 [==============================] - 0s 200us/step - loss: 11.6495
Epoch 7/10
100/100 [==============================] - 0s 210us/step - loss: 10.5554
Epoch 8/10
100/100 [==============================] - 0s 200us/step - loss: 10.1424
Epoch 9/10
100/100 [==============================] - 0s 190us/step - loss: 9.9740
Epoch 10/10
100/100 [==============================] - 0s 210us/step - loss: 9.7576


In [48]:
m.predict(inputs)

array([[13.476523 ],
       [18.55334  ],
       [17.502335 ],
       [15.611809 ],
       [14.864271 ],
       [ 6.0128922],
       [13.07029  ],
       [12.002965 ],
       [12.280859 ],
       [12.132752 ],
       [13.639253 ],
       [16.524067 ],
       [ 8.607734 ],
       [14.347007 ],
       [11.422089 ],
       [14.94438  ],
       [11.676466 ],
       [11.11404  ],
       [ 8.575901 ],
       [12.778757 ],
       [ 9.477356 ],
       [ 9.552375 ],
       [12.311485 ],
       [11.236767 ],
       [13.934259 ],
       [13.672296 ],
       [11.338783 ],
       [12.125227 ],
       [10.203859 ],
       [10.528301 ],
       [11.04338  ],
       [10.52457  ],
       [ 9.042562 ],
       [13.827157 ],
       [ 8.379091 ],
       [ 9.133368 ],
       [15.2446575],
       [10.818372 ],
       [12.910782 ],
       [11.684388 ],
       [10.761657 ],
       [13.331409 ],
       [ 8.621158 ],
       [15.761568 ],
       [11.919111 ],
       [14.196828 ],
       [11.67553  ],
       [12.08

In [49]:
output.as_matrix()

C:\Users\Ger\Ana\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([15, 17, 11, 12, 14, 12, 15, 11, 13, 10, 12, 17, 10, 14, 12, 11, 16,
       12, 11, 10, 12, 11, 15, 11, 11, 14, 15, 11, 17, 10, 10, 11, 11, 19,
        8, 13, 16, 14, 10, 12, 12, 14, 10, 13, 14, 11, 15, 10, 15, 12, 13,
       12, 10, 11, 10, 11, 10, 14, 10, 11, 11, 11, 13, 19, 14, 14,  8, 12,
       11, 11, 11, 16, 13, 12, 12, 18, 12, 16, 11,  8,  8, 12, 18,  9, 16,
       13,  9, 16,  9, 11, 16, 13,  8, 14, 15, 10, 11, 12, 16, 14],
      dtype=int64)

In [50]:
np.around(m.predict(inputs).T)

array([[13., 19., 18., 16., 15.,  6., 13., 12., 12., 12., 14., 17.,  9.,
        14., 11., 15., 12., 11.,  9., 13.,  9., 10., 12., 11., 14., 14.,
        11., 12., 10., 11., 11., 11.,  9., 14.,  8.,  9., 15., 11., 13.,
        12., 11., 13.,  9., 16., 12., 14., 12., 12.,  9.,  9., 17.,  8.,
         9., 11., 14., 13., 12., 13., 12.,  8.,  9., 17., 13., 12., 11.,
        14.,  1., 13., 16., 13., 10., 14.,  8., 14.,  5., 13., 10., 10.,
        11., 11.,  9., 17., 15.,  9., 14., 17., 12., 12., 15., 13., 16.,
        16., 12., 12., 11., 11., 10., 12., 14., 14.]], dtype=float32)

In [20]:
import keras as kr

Using TensorFlow backend.


In [42]:
m.predict(inputs).T - output.as_matrix()

C:\Users\Ger\Ana\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[-2.51367569, -4.57554817,  1.40816307,  0.53562641, -1.48571396,
         0.0983696 , -2.89160728,  1.47816086, -0.59658432,  2.31494808,
         0.38387966, -4.5782032 ,  2.35458755, -1.49259853,  0.57620811,
         1.48417187, -3.55314255,  0.11242962,  1.15917778,  2.59237385,
         0.23230553,  1.40810394, -2.77880669,  1.28560543,  1.5423336 ,
        -1.53361225, -2.60045624,  1.12203217, -4.53740311,  2.26638031,
         2.33882236,  1.53631783,  1.11649323, -6.53336143,  4.30270576,
        -0.5171814 , -3.49253654, -1.54105377,  2.6079731 ,  0.37548828,
         0.46241093, -1.43777466,  2.15729332, -0.83671188, -1.57990646,
         1.18789864, -2.52298737,  2.498312  , -2.83584881,  0.18953323,
        -0.47119331,  0.44501209,  2.46442318,  1.20465279,  2.29002571,
         1.24141407,  2.29990578, -1.48169899,  2.14923668,  1.24661255,
         1.2254715 ,  1.47037506, -0.54045963, -6.62439537, -1.88593197,
        -1.5409584 ,  3.06240463,  0.36606598,  1.5

In [43]:
###difference between what the neuron is predicting and the actual values we told it to predict
np.sqrt(np.sum((m.predict(inputs).T - output.as_matrix())**2))

C:\Users\Ger\Ana\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


25.07687453836791